###############################################################
# 全局设置
################################################################

# 激活调试模式 （默认关闭）
debug = false

# 日志等级 （默认 ERROR）
logLevel = "INFO"

# 全局入口点类型 （默认 http）
#defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]

# 不上报统计信息
sendAnonymousUsage = false

################################################################
# 入口点设置
################################################################

[entryPoints]

    # 默认前端
    [entryPoints.http]
        address = ":80"
        compress = true
    [entryPoints.spring]
        address = ":8360"
# 根据自己情况选择是否进行自动跳转
#        [entryPoints.http.redirect]
#            entryPoint = "https"
#    [entryPoints.https]
#        address = ":443"
#        compress = true
#    [entryPoints.https.tls]
#        [[entryPoints.https.tls.certificates]]
#            certFile = "/data/ssl/lab.com.crt"
#            keyFile = "/data/ssl/lab.com.key"

    # 控制台端口
    [entryPoints.traefik-api]
        address = ":4399"
# 如果不想公开控制台，可以参考下面的配置生成你自己的 BA 账号密码
        [entryPoints.traefik-api.auth]
            [entryPoints.traefik-api.auth.basic]
                #htpasswd -nb soulteary soulteary
		users = ["baisheng:$apr1$jfu00Ykt$ZXZwEGbTn8Gq1ND33SloF/","admin:$apr1$uSjZJvnR$tsJxOce5ibB2PdkhV8Hub/"]
                #users = ["soulteary:$apr1$hVv8KPU8$IiTLEE5QYKgd4mZuCXpOD."]
#        [entryPoints.traefik-api.redirect]
#            entryPoint = "https"

    # Ping端口
    [entryPoints.traefik-ping]
        address = ":4398"
#        [entryPoints.traefik-ping.redirect]
#            entryPoint = "https"

################################################################
# Traefik File configuration
################################################################

[file]
    [backends]
        [backends.dashboard]
            [backends.dashboard.servers.server1]
                url = "http://127.0.0.1:4399"
        [backends.ping]
            [backends.ping.servers.server1]
                url = "http://127.0.0.1:4398"
        [backends.chinauff]
            [backends.chinauff.servers.server1]
                url = "http://127.0.0.1:4399"
        [backends.springH5]
            [backends.springH5.servers.server1]
                #url = "http://192.168.25.88:8360"
                url = "http://192.168.25.88:3000"
        [backends.springServer]
            [backends.springServer.servers.server1]
                url = "http://192.168.25.88:5000"
        [backends.sre]
            [backends.sre.servers.server1]
                url = "http://192.168.25.88:9988"
    [frontends]
        [frontends.springH5]
            entryPoints = ["spring","http"]
            priority = 5 
            backend = "springH5"
            [frontends.springH5.routes.route01]
                #rule = "PathPrefixStrip:/spring"
                rule = "PathPrefix:/spring"
        [frontends.springApiServer]
            entryPoints = ["spring"]
            priority = 10
            backend = "springServer"
            [frontends.springApiServer.routes.route01]
                rule = "PathPrefixStrip:/spring/server"
                #rule = "PathPrefixStrip:/spring"
                #rule = "ReplacePathRegex: ^/ /spring"
                #rule = "Host:spring.chinauff.com"
            #[frontends.springServer.routes.route02]
            #    rule = "Host:spring.chinauff.com"
                #rule = "PathPrefixStrip:/spring/server"
        [frontends.springAdminServer]
            entryPoints = ["http"]
            backend = "springServer"
            [frontends.springAdminServer.routes.route01]
                rule = "Host:spring.chinauff.com"
        #        type = "PathPrefixStrip"
        #        rule = "PathPrefixStrip:/test"
        ### 服务管理面板
        [frontends.dashboard]
            entryPoints = ["http"]
            priority = 100 
            backend = "dashboard"
            [frontends.dashboard.routes.route01]
                rule = "PathPrefixStrip:/control"
        ### 运维部署服务
        [frontends.sre]
            entryPoints = ["http"]
            backend = "sre"
            [frontends.sre.routes.route01]
                rule = "PathPrefixStrip:/sre"
        [frontends.ping]
            # entrypoints = ["https"]
            backend = "ping"
            [frontends.ping.routes.route01]
                rule = "Host:ping.lab.com"
            [frontends.ping.routes.route02]
                rule = "ReplacePathRegex: ^/ /ping"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
# Default: os.Stdout
[traefikLog]
  filePath = "/data/logs/traefik.log"

[accessLog]
  filePath = "/data/logs/access.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# 访问日志 配置
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API 及 控制台 配置
################################################################

# 启用API以及控制台
[api]
    # 入口点名称
    entryPoint = "traefik-api"

    # 开启控制台（默认开启）
    dashboard = true

    # 默认协议
    defaultEntryPoints = ["http"]

################################################################
# Ping 配置
################################################################

# 启用 ping
[ping]
    # 入口点名称
    entryPoint = "traefik-ping"

################################################################
# Docker 后端配置
################################################################

# 启用Docker后端
[docker]

# Docker服务后端
endpoint = "unix:///var/run/docker.sock"
# 默认域名
domain = "spring.chinauff.com"
# 监控docker变化
watch = true

# 使用自定义模板（可选）
# filename = "docker.tmpl"

# 对容器默认进行暴露（默认开启）
#   如果关闭选项，则容器不包含 `traefik.enable=true` 标签，就不会被暴露
# 没有设置`traefik.enable=true`的容器就不会被发现
exposedbydefault = false

# 使用绑定端口的IP地址取代内部私有网络（默认关闭）
usebindportip = false

# 使用 Swarm Mode （默认关闭）
swarmmode = false

# Enable docker TLS connection.
#
# Optional
#
#  [docker.tls]
#  ca = "/etc/ssl/ca.crt"
#  cert = "/etc/ssl/docker.crt"
#  key = "/etc/ssl/docker.key"
#  insecureskipverify = true

